Etammen/Controllers/ClinicAdminController.cs
using BusinessLogicLayer.Interfaces;
using Etammen.Mapping.ClinicForAdmin;
using Etammen.ViewModels.Admin.Clinic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Etammen.Controllers
{
    public class ClinicAdminController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ClinicAdminMapper _mapper;
        public ClinicAdminController(IUnitOfWork unitOfWork, ClinicAdminMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        public async Task<IActionResult> Index()
        {
            var clinics = await _unitOfWork.Clinics.FindAllBy(e => e.IsDeleted == false, new[] { "Doctor" });
            var clinicViewModels = _mapper.MapClinicsToGetAllViewModel(clinics);
            return View(clinicViewModels);
        }

        public async Task<IActionResult> Details(int id)
        {
            var clinic = await _unitOfWork.Clinics.FindBy(e => e.Id == id, new[] { "Doctor" });
            var doctorId = clinic.DoctorId;
            var doctor = await _unitOfWork.Doctors.FindBy(e => e.Id == doctorId, new[] { "ApplicationUser" });
            var clinicViewModel = _mapper.MapOneClinicToViewModel(clinic);
            clinicViewModel.DoctorFirstName = doctor.ApplicationUser.FirstName;
            clinicViewModel.DoctorLastName = doctor.ApplicationUser.LastName;
            return View(clinicViewModel);
        }


        public async Task<IActionResult> Delete(int id)
        {
            var clinic = await _unitOfWork.Clinics.FindBy(e => e.Id == id, new[] { "Doctor" });
            var doctorId = clinic.DoctorId;
            var doctor = await _unitOfWork.Doctors.FindBy(e => e.Id == doctorId, new[] { "ApplicationUser" });
            var clinicViewModel = _mapper.MapOneClinicToViewModel(clinic);
            clinicViewModel.DoctorFirstName = doctor.ApplicationUser.FirstName;
            clinicViewModel.DoctorLastName = doctor.ApplicationUser.LastName;
            return View(clinicViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(GetOneClinicViewModel clinicViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var clinic = await _unitOfWork.Clinics.FindBy(e => e.Id == clinicViewModel.Id);
                    clinic.IsDeleted = true;
                    clinic.DeletionDate = DateOnly.FromDateTime(DateTime.Now);
                    await _unitOfWork.Clinics.Delete(clinic.Id);
                    await _unitOfWork.Commit();
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(clinicViewModel);
            }
        }
    }
}

Etammen/Controllers/DoctorAdminController.cs
using AutoMapper;
using BusinessLogicLayer.Interfaces;
using DataAccessLayerEF.Models;
using Etammen.Mapping.DoctorForAdmin;
using Etammen.Services.Email;
using Etammen.ViewModels.Admin.Doctor;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Numerics;

namespace Etammen.Controllers
{
    [Route("doctorAdmin")]
    public class DoctorAdminController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly DoctorsAdminMapper _doctorsMapper;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailService _emailService;
        public DoctorAdminController(IUnitOfWork unitOfWork, DoctorsAdminMapper getAllDoctorsMapper, IMapper mapper,
            UserManager<ApplicationUser> applicationUser, IEmailService emailService)
        {
            _unitOfWork = unitOfWork;
            _doctorsMapper = getAllDoctorsMapper;
            _mapper = mapper;
            _userManager = applicationUser;
            _emailService = emailService;
        }
        [Route("GetAllDoctors")]
        public async Task<IActionResult> Index()
        {
            var doctors = await _unitOfWork.Doctors.FindAllBy(e => e.IsDeleted == false, new[] { "ApplicationUser" });
            var doctorsViewModel = _doctorsMapper.MapDoctorsToViewModel(doctors);
            return View(doctorsViewModel);
        }
        [Route("GetDoctorDetails/{id:int:min(1)}")]
        public async Task<IActionResult> Details(int id)
        {
            var doctor = await _unitOfWork.Doctors.FindBy(e => e.Id == id, new[] { "ApplicationUser" });
            var doctorViewModel = _doctorsMapper.MapOneDoctorToViewModel(doctor);
            doctorViewModel.Clinics = await _unitOfWork.Clinics.FindAllBy(e => e.DoctorId == id);
            return View(doctorViewModel);

        }
        [Route("DeleteDoctor/{id:int:min(1)}")]

        public async Task<IActionResult> Delete(int id)
        {
            var doctor = await _unitOfWork.Doctors.FindBy(e => e.Id == id, new[] { "ApplicationUser" });
            var doctorViewModel = _doctorsMapper.MapOneDoctorToViewModel(doctor);
            doctorViewModel.Clinics = await _unitOfWork.Clinics.FindAllBy(e => e.DoctorId == id);
            return View(doctorViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("DeleteDoctor/{id:int:min(1)}")]
        public async Task<IActionResult> Delete(int id,GetDoctorByIdViewModel doctorViewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var doctor = await _unitOfWork.Doctors.FindBy(e => e.Id == doctorViewModel.Id);
                    doctor.IsDeleted = true;
                    doctor.DeletionDate = DateOnly.FromDateTime(DateTime.Now);
                    await _unitOfWork.Doctors.Delete(doctor.Id);
                    await _unitOfWork.Commit();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(doctorViewModel);
            }
        }
        [Route("ApproveDoctor")]
        public async Task<IActionResult> Approve()
        {
            string[] includes = ["ApplicationUser"];
            IEnumerable<Doctor> Doctors = await _unitOfWork.Doctors.FindAllBy((D => D.IsRegistered == false && D.IsDeleted == false), includes);
            IEnumerable<ApproveDoctorViewModel> mappedDoctors =
                _mapper.Map<IEnumerable<Doctor>, IEnumerable<ApproveDoctorViewModel>>(Doctors);
            return View(mappedDoctors);
        }
        [Route("ApproveDoctor/{id:int}/{isApproved:bool}")]
        public async Task<IActionResult> ApprovePost(int id, bool isApproved)
        {
            Doctor doctor = await _unitOfWork.Doctors.FindBy((D) => D.Id == id && D.IsDeleted == false, ["ApplicationUser"]);
            if (isApproved)
            {
                doctor.IsRegistered = true;
                _unitOfWork.Doctors.Update(doctor);

                string rejectionMailBody = "we are glad to inform you that the documents you provided for you Etammen's account verification was accepted," +
                     " you can now log in to your account, best wishes doctor!";
                string rejectionMailSubject = "Etammen account Documents Verification Update";

                await SendStatusUpdateEmail(doctor.ApplicationUser.Email, rejectionMailSubject, rejectionMailBody);
                
            }
            else
            {
                _unitOfWork.Doctors.Delete(doctor.Id, true);
                await _userManager.DeleteAsync(doctor.ApplicationUser);

                string rejectionMailBody = "we are sorry to inform you that the documents you provided for you Etammen's account verification was not accepted," +
                    " please try to provide valid documents and register again";
                string rejectionMailSubject = "Etammen account Documents Verification Update";

                await _emailService.SendEmailAsync(new Message(doctor.ApplicationUser.Email,rejectionMailSubject, rejectionMailBody));

                await SendStatusUpdateEmail(doctor.ApplicationUser.Email, rejectionMailSubject, rejectionMailBody);

            }
            int rows = await _unitOfWork.Commit();
            return RedirectToAction(nameof(Approve));
        }

        private async Task SendStatusUpdateEmail(string email,string rejectionMailBody, string rejectionMailSubject)
        {
            await _emailService.SendEmailAsync(new Message(email, rejectionMailSubject, rejectionMailBody));
        }
    }
}

Etammen/Views/Shared/Error403.cshtml
@model ErrorViewModel

<!DOCTYPE html>
<html>
<head>
    <title>403 not authorized</title>

</head>
<body>
    <img src="/assets/images/backgrounds/403ErrorPic.jpg" class="img-fluid" />
</body>
</html>

Etammen/Views/Shared/Error404.cshtml
@model ErrorViewModel

<!DOCTYPE html>
<html>
<head>
    <title>404 not found</title>
</head>
<body>
    <img src="/assets/images/backgrounds/404ErrorPic.png" class="img-fluid"/>
</body>
</html>

Etammen/Views/Shared/_HomePatientLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>

    <div>
        @RenderBody()
    </div>
</body>
</html>

Etammen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <title>@ViewData["Title"] - Etammen</title>
    <title>Etammen</title>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="/assets/img/favicon.png" rel="icon">
    <link href="/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="/assets/css/style.css" rel="stylesheet">

    <!--Views head -->
    @RenderSection("Head", required: false)

    <!-- Template Main CSS File -->
    <link href="/assets/css/style.css" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/PatientAll.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.css" />
    <link rel="stylesheet" href="/DataTables/datatables.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
    <style>
        html, body {
            height: 100%;
        }

        .wrapper {
            display: flex;
            flex-direction: column;
            min-height: 1000px;
        }

        .section {
            padding-top: 0px;
        }
    </style>


</head>
<body>

    <div class="wrapper">


        <!-- ======= Top Bar ======= -->
        <div id="topbar" class="d-flex align-items-center">
            <div class="container d-flex justify-content-between">
                <div class="contact-info d-flex align-items-center">
                    <i class="bi bi-envelope"></i> <a href="mailto:etammenwebsite@gmail.com">Etammen@Gmail.com</a>
                </div>
                <div class="d-none d-lg-flex social-links align-items-center ml-auto">
                </div>
                <div class="d-none d-lg-flex social-links align-items-center">

                    @if (!User.Identity.IsAuthenticated)
                    {
                        <a class="nav-link text-dark" asp-controller="Account" asp-action="Register">Sign Up</a>
                        <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">Log In</a>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        <span class="nav-link text-dark">Hello, @User.Identity.Name</span>
                        <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Log out</a>
                    }


                </div>
            </div>
        </div>

        <!-- ======= Header ======= -->

        <header id="header">

            <div class="container d-flex align-items-center">

                <h1 class="logo me-auto"><a href="/">Etammen</a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>

                <nav id="navbar" class="navbar order-last order-lg-0">
                    <ul>
                        @if (User.IsInRole("Doctor"))
                        {
                            <li class="dropdown">
                                <a class="nav-link scrollto"><span>Dashboard</span> <i class="bi bi-chevron-down"></i></a>
                                <ul>
                                    <li><a asp-action="Profile" asp-controller="Doctors">Profile</a></li>
                                    <li><a asp-action="AppointmentIndex" asp-controller="Doctors">Appointments</a></li>
                                    <li><a asp-action="ClinicIndex" asp-controller="Doctors">Clinics</a></li>
                                    <li><a asp-action="DeactivateAccount" asp-controller="Doctors">Deactivate Account</a></li>
                                </ul>
                            </li>
                        } 
                         @if (User.IsInRole("Admin"))
                         {
                            <li><a asp-action="Index" asp-controller="DoctorAdmin">Admin Dashboard</a></li>
                         } 
                        @if (User.IsInRole("Patient"))
                        {
                            <li class="dropdown">
                                <a class="nav-link scrollto"><span>Dashboard</span> <i class="bi bi-chevron-down"></i></a>
                                <ul>
                                    <li><a asp-action="Profile" asp-controller="Patient">Profile</a></li>
                                    <li><a asp-action="AppointmentIndex" asp-controller="Patient">Appointments</a></li>
                                </ul>
                         
                            </li>
                        }
                    </ul>

                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
        </div>
    </header><!-- End Header --> 
    <!-- ======= Hero Section ======= -->
        <main id="main" class="d-flex justify-content-center pt-5 flex-grow-1">
        <section class="container">
            @RenderBody()
        </section>
    </main>
    <!-- ======= Footer ======= -->
        <footer id="footer" class="footer">
            <div class="footer-top">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-4 col-md-4 footer-contact">
                            <h3>Etammen</h3>
                            <p>
                                He who has health, has hope.<br />
                                He who has hope, has everything.<br />
                                <strong>Email:</strong> etammenwebsite@example.com<br>
                            </p>
                        </div>

                        <div class="col-lg-4 col-md-4 footer-links">
                            <h4>Useful Links</h4>
                            <ul>
                                <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a asp-controller="Account" asp-action="RegisterDoctor">Etammen For Doctors</a></li>

                            </ul>
                        </div>
                        <div class="col-lg-4 col-md-4 footer-links">
                            <h4>About us</h4>
                            <p>Etammen was established in 2024 to act as a gateway between people and doctors.</p>
                            <p>All Rights reserved &copy; Tigers Team &#64; ITI</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container d-md-flex py-4">
                <div class="social-links text-center text-md-right pt-3 pt-md-0">
                    <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                    <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                    <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                    <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                </div>
            </div>
        </footer>
        </div>
    @* <div id="preloader"></div> *@
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!----------------scripts------------------>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <partial name="_ValidationScriptsPartial" />
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Vendor JS Files -->
    <script src="/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <!-- Template Main JS File -->

    <script src="assets/js/main.js"></script>
    <script src="~/AdminAssets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/AdminAssets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/AdminAssets/js/sidebarmenu.js"></script>
    <script src="~/AdminAssets/js/app.min.js"></script>
    <script src="~/AdminAssets/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="~/AdminAssets/libs/simplebar/dist/simplebar.js"></script>
    <script src="~/AdminAssets/js/dashboard.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.js"></script>
    <script src="/DataTables/datatables.js"></script>

    <script src="assets/js/main.js"></script>
    <script src="~/AdminAssets/libs/jquery/dist/jquery.min.js"></script>
    <script src="~/AdminAssets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/AdminAssets/js/sidebarmenu.js"></script>
    <script src="~/AdminAssets/js/app.min.js"></script>
    <script src="~/AdminAssets/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="~/AdminAssets/libs/simplebar/dist/simplebar.js"></script>
    <script src="~/AdminAssets/js/dashboard.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.js"></script>
    <script src="/DataTables/datatables.js"></script>

    <script src="/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("DTSection", required: false)
</body>
</html>

Etammen/Views/Shared/_PartialViewHeaderStart.cshtml
<header class="app-header">
    <nav class="navbar navbar-expand-lg navbar-light">
        <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
                <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                    <i class="ti ti-menu-2"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                    <i class="ti ti-bell-ringing"></i>
                    <div class="notification bg-primary rounded-circle"></div>
                </a>
            </li>
        </ul>
        <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
            <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                <li class="nav-item dropdown">
                    <a class="nav-link nav-icon-hover" href="javascript:void(0)" id="drop2" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        <img src="~/AdminAssets/images/profile/user-1.jpg" alt="" width="35" height="35" class="rounded-circle">
                    </a>
                    <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                        <div class="message-body">
                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                <i class="ti ti-user fs-6"></i>
                                <p class="mb-0 fs-3">My Profile</p>
                            </a>
                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                <i class="ti ti-mail fs-6"></i>
                                <p class="mb-0 fs-3">My Account</p>
                            </a>
                            <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                <i class="ti ti-list-check fs-6"></i>
                                <p class="mb-0 fs-3">My Task</p>
                            </a>
                            <a href="./authentication-login.html" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</header>

Etammen/Views/Shared/_PartialViewSideBar.cshtml
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div>
        <div class="brand-logo d-flex align-items-center justify-content-between">
            <h1 class="logo me-auto"><a href="/">Etammen</a></h1>
            <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                <i class="ti ti-x fs-8"></i>
            </div>
        </div>
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
            <ul id="sidebarnav">
                <li class="nav-small-cap">
                    <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                    <span class="hide-menu">Entities</span>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="DoctorAdmin" asp-action="Index" aria-expanded="false">
                        <span>
                            <i class="fa-solid fa-user-doctor"></i>
                        </span>
                        <span class="hide-menu">Doctor</span>
                    </a>
                </li>

                <li class="sidebar-item">

                    <a class="sidebar-link" asp-controller="DoctorAdmin" asp-action="Approve" aria-expanded="false">
                        <span>
                            <i class="fa-solid fa-user-doctor"></i>
                        </span>
                        <span class="hide-menu">Approve Doctors</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="ClinicAdmin" asp-action="Index" aria-expanded="false">
                        <span>
                            <i class="fa-solid fa-house-chimney-medical"></i>
                        </span>
                        <span class="hide-menu">Clinic</span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="PatientAdmin" asp-action="Index" aria-expanded="false">
                        <span>
                            <i class="fa-solid fa-hospital-user"></i>
                        </span>
                        <span class="hide-menu">Patient</span>
                    </a>
                </li>
            </ul>

        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>